// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyzogjengmqoqnpfqnda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5em9namVuZ21xb3FucGZxbmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTk2MDIsImV4cCI6MjA2ODg3NTYwMn0.qQ8A69mr-K7lc29S-govr2nYfdsVK_4Vozg3L8yg0Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});